# Generated by Django 5.2.6 on 2025-09-29 08:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('schools', '0003_remove_school_cover_remove_school_slug_and_more'),
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AddIndex(
            model_name='profile',
            index=models.Index(fields=['school', 'role'], name='users_profi_school__460f19_idx'),
        ),
        migrations.AddIndex(
            model_name='profile',
            index=models.Index(fields=['school'], name='users_profi_school__e040e6_idx'),
        ),
    ]
