# Generated by Django 5.2.6 on 2025-09-29 11:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_profile_users_profi_school__460f19_idx_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='AdminProfile',
            fields=[
            ],
            options={
                'verbose_name': 'Admin',
                'verbose_name_plural': 'Admins',
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('users.profile',),
        ),
        migrations.CreateModel(
            name='CommitteeProfile',
            fields=[
            ],
            options={
                'verbose_name': 'Committee',
                'verbose_name_plural': 'Committees',
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('users.profile',),
        ),
        migrations.CreateModel(
            name='ParentProfile',
            fields=[
            ],
            options={
                'verbose_name': 'Parent',
                'verbose_name_plural': 'Parents',
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('users.profile',),
        ),
    ]
