# Generated by Django 4.2.7 on 2025-10-14 12:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0006_profile_designation'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='educational_qualification',
            field=models.CharField(blank=True, help_text='Educational qualification (e.g., B.A., M.A., B.Ed.)', max_length=200, null=True),
        ),
    ]
