# Generated by Django 4.2.7 on 2025-11-17 15:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0009_profile_blood_group'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='income',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Monthly income (numeric)', max_digits=12, null=True),
        ),
        migrations.AddField(
            model_name='profile',
            name='occupation',
            field=models.CharField(blank=True, help_text='Occupation of the user (parent/guardian)', max_length=120, null=True),
        ),
    ]
