# Generated by Django 4.2.7 on 2026-01-13 17:37

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('schools', '0003_remove_school_cover_remove_school_slug_and_more'),
        ('users', '0010_profile_income_profile_occupation'),
    ]

    operations = [
        migrations.CreateModel(
            name='AssistantMemory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('key', models.CharField(max_length=200)),
                ('data', models.JSONField(default=dict)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('school', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='assistant_memory', to='schools.school')),
            ],
            options={
                'indexes': [models.Index(fields=['school', 'key'], name='users_assis_school__5710e9_idx')],
                'unique_together': {('school', 'key')},
            },
        ),
        migrations.CreateModel(
            name='AssistantLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('query_text', models.TextField()),
                ('intent', models.CharField(blank=True, max_length=100, null=True)),
                ('params', models.JSONField(default=dict)),
                ('result_summary', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('school', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='assistant_logs', to='schools.school')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='assistant_logs', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['school', 'intent'], name='users_assis_school__6645dd_idx'), models.Index(fields=['created_at'], name='users_assis_created_bb4212_idx')],
            },
        ),
    ]
