# Generated by Django 4.2.7 on 2026-04-03 10:14

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0012_assistantknowledge_aichatsession_aichatmessage'),
    ]

    operations = [
        migrations.AlterField(
            model_name='aichatsession',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='ai_sessions', to=settings.AUTH_USER_MODEL),
        ),
    ]
