# Generated by Django 5.2.6 on 2025-09-29 08:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('academics', '0003_classroom_academics_c_school__339c02_idx_and_more'),
        ('fees', '0001_initial'),
        ('schools', '0003_remove_school_cover_remove_school_slug_and_more'),
    ]

    operations = [
        migrations.AddIndex(
            model_name='feestructure',
            index=models.Index(fields=['school', 'name'], name='fees_feestr_school__996244_idx'),
        ),
        migrations.AddIndex(
            model_name='feestructure',
            index=models.Index(fields=['school'], name='fees_feestr_school__736831_idx'),
        ),
        migrations.AddIndex(
            model_name='payment',
            index=models.Index(fields=['student', 'date'], name='fees_paymen_student_0ee9ab_idx'),
        ),
        migrations.AddIndex(
            model_name='payment',
            index=models.Index(fields=['date'], name='fees_paymen_date_67f4f4_idx'),
        ),
    ]
