# Generated by Django 5.2.6 on 2025-09-29 19:17

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('academics', '0005_studentprofile_guardian_studentprofile_guardian_name'),
        ('fees', '0002_feestructure_fees_feestr_school__996244_idx_and_more'),
        ('schools', '0003_remove_school_cover_remove_school_slug_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='FeeCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('fee_type', models.CharField(choices=[('tuition', 'Tuition Fee'), ('admission', 'Admission Fee'), ('exam', 'Examination Fee'), ('transport', 'Transport Fee'), ('library', 'Library Fee'), ('sports', 'Sports Fee'), ('lab', 'Laboratory Fee'), ('other', 'Other')], default='other', max_length=20)),
                ('description', models.TextField(blank=True)),
                ('is_mandatory', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name_plural': 'Fee Categories',
            },
        ),
        migrations.CreateModel(
            name='FeeCollection',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('month', models.PositiveIntegerField()),
                ('year', models.PositiveIntegerField()),
                ('total_expected', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('total_collected', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('total_pending', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('collection_percentage', models.DecimalField(decimal_places=2, default=0, max_digits=5)),
            ],
            options={
                'ordering': ['-year', '-month'],
            },
        ),
        migrations.CreateModel(
            name='StudentFeeAssignment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('custom_amount', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('discount_percentage', models.DecimalField(decimal_places=2, default=0, max_digits=5)),
                ('discount_reason', models.CharField(blank=True, max_length=200)),
                ('is_waived', models.BooleanField(default=False)),
                ('waiver_reason', models.TextField(blank=True)),
                ('assigned_date', models.DateField(auto_now_add=True)),
            ],
        ),
        migrations.AlterModelOptions(
            name='payment',
            options={'ordering': ['-payment_date', '-created_at']},
        ),
        migrations.RemoveIndex(
            model_name='feestructure',
            name='fees_feestr_school__996244_idx',
        ),
        migrations.RemoveIndex(
            model_name='feestructure',
            name='fees_feestr_school__736831_idx',
        ),
        migrations.RemoveIndex(
            model_name='payment',
            name='fees_paymen_student_0ee9ab_idx',
        ),
        migrations.RemoveIndex(
            model_name='payment',
            name='fees_paymen_date_67f4f4_idx',
        ),
        migrations.RemoveField(
            model_name='feestructure',
            name='name',
        ),
        migrations.RemoveField(
            model_name='payment',
            name='date',
        ),
        migrations.RemoveField(
            model_name='payment',
            name='fee',
        ),
        migrations.AddField(
            model_name='feestructure',
            name='academic_year',
            field=models.CharField(blank=True, help_text='e.g., 2024-2025', max_length=20),
        ),
        migrations.AddField(
            model_name='feestructure',
            name='classroom',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='fee_structures', to='academics.classroom'),
        ),
        migrations.AddField(
            model_name='feestructure',
            name='frequency',
            field=models.CharField(choices=[('monthly', 'Monthly'), ('quarterly', 'Quarterly'), ('half_yearly', 'Half Yearly'), ('yearly', 'Yearly'), ('one_time', 'One Time')], default='monthly', max_length=20),
        ),
        migrations.AddField(
            model_name='feestructure',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='feestructure',
            name='late_fee_after_days',
            field=models.PositiveIntegerField(default=7, help_text='Days after due date'),
        ),
        migrations.AddField(
            model_name='feestructure',
            name='late_fee_amount',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
        migrations.AddField(
            model_name='payment',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AddField(
            model_name='payment',
            name='created_by',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='payment',
            name='installment_number',
            field=models.PositiveIntegerField(default=1),
        ),
        migrations.AddField(
            model_name='payment',
            name='payment_date',
            field=models.DateField(default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name='payment',
            name='payment_method',
            field=models.CharField(choices=[('cash', 'Cash'), ('bank_transfer', 'Bank Transfer'), ('cheque', 'Cheque'), ('online', 'Online Payment'), ('mobile_banking', 'Mobile Banking (bKash/Nagad/Rocket)'), ('card', 'Credit/Debit Card')], default='cash', max_length=20),
        ),
        migrations.AddField(
            model_name='payment',
            name='payment_status',
            field=models.CharField(choices=[('pending', 'Pending'), ('completed', 'Completed'), ('failed', 'Failed'), ('refunded', 'Refunded')], default='completed', max_length=20),
        ),
        migrations.AddField(
            model_name='payment',
            name='receipt_number',
            field=models.CharField(blank=True, max_length=50, null=True, unique=True),
        ),
        migrations.AddField(
            model_name='payment',
            name='remarks',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='payment',
            name='transaction_id',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AddField(
            model_name='payment',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, null=True),
        ),
        migrations.AlterField(
            model_name='feestructure',
            name='due_day',
            field=models.PositiveIntegerField(default=10, help_text='Day of month for payment'),
        ),
        migrations.AlterField(
            model_name='payment',
            name='reference',
            field=models.CharField(blank=True, default='', help_text='Cheque number, receipt number, etc.', max_length=200),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='feecategory',
            name='school',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='fee_categories', to='schools.school'),
        ),
        migrations.AddField(
            model_name='feestructure',
            name='category',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='structures', to='fees.feecategory'),
        ),
        migrations.AddIndex(
            model_name='feestructure',
            index=models.Index(fields=['school', 'classroom'], name='fees_feestr_school__32557e_idx'),
        ),
        migrations.AddIndex(
            model_name='feestructure',
            index=models.Index(fields=['is_active'], name='fees_feestr_is_acti_c62141_idx'),
        ),
        migrations.AddField(
            model_name='feecollection',
            name='classroom',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='fee_collections', to='academics.classroom'),
        ),
        migrations.AddField(
            model_name='feecollection',
            name='school',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='fee_collections', to='schools.school'),
        ),
        migrations.AddField(
            model_name='studentfeeassignment',
            name='fee_structure',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='assignments', to='fees.feestructure'),
        ),
        migrations.AddField(
            model_name='studentfeeassignment',
            name='student',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='fee_assignments', to='academics.studentprofile'),
        ),
        migrations.AddField(
            model_name='payment',
            name='fee_assignment',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='payments', to='fees.studentfeeassignment'),
        ),
        migrations.AddIndex(
            model_name='payment',
            index=models.Index(fields=['student', 'payment_date'], name='fees_paymen_student_ed705a_idx'),
        ),
        migrations.AddIndex(
            model_name='payment',
            index=models.Index(fields=['payment_date'], name='fees_paymen_payment_1bd5e4_idx'),
        ),
        migrations.AddIndex(
            model_name='payment',
            index=models.Index(fields=['receipt_number'], name='fees_paymen_receipt_755eab_idx'),
        ),
        migrations.AddIndex(
            model_name='payment',
            index=models.Index(fields=['payment_status'], name='fees_paymen_payment_ee1050_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='feecategory',
            unique_together={('school', 'name')},
        ),
        migrations.AlterUniqueTogether(
            name='feecollection',
            unique_together={('school', 'classroom', 'month', 'year')},
        ),
        migrations.AlterUniqueTogether(
            name='studentfeeassignment',
            unique_together={('student', 'fee_structure')},
        ),
    ]
