# Generated by Django 4.2.7 on 2025-11-05 16:58

from decimal import Decimal
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('schools', '0003_remove_school_cover_remove_school_slug_and_more'),
        ('academics', '0007_alter_teacherassignment_teacher'),
        ('fees', '0003_feecategory_feecollection_studentfeeassignment_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='FeeSlip',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('month', models.PositiveIntegerField()),
                ('year', models.PositiveIntegerField()),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('amount_paid', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=10)),
                ('status', models.CharField(choices=[('unpaid', 'Unpaid'), ('partial', 'Partial'), ('paid', 'Paid'), ('void', 'Void')], default='unpaid', max_length=10)),
                ('due_date', models.DateField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('classroom', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='fee_slips', to='academics.classroom')),
                ('fee_structure', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='fee_slips', to='fees.feestructure')),
                ('school', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='fee_slips', to='schools.school')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='fee_slips', to='academics.studentprofile')),
            ],
            options={
                'indexes': [models.Index(fields=['school', 'classroom', 'month', 'year'], name='fees_feesli_school__0009bb_idx'), models.Index(fields=['student', 'month', 'year'], name='fees_feesli_student_8ac413_idx')],
                'unique_together': {('student', 'fee_structure', 'month', 'year')},
            },
        ),
    ]
