# Generated by Django 4.2.7 on 2025-11-15 08:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fees', '0004_feeslip'),
    ]

    operations = [
        migrations.AlterField(
            model_name='payment',
            name='payment_status',
            field=models.CharField(choices=[('pending', 'Pending'), ('completed', 'Completed'), ('failed', 'Failed'), ('refunded', 'Refunded')], default='pending', max_length=20),
        ),
    ]
