# Generated by Django 5.2.6 on 2025-09-24 14:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('schools', '0002_school_address'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='school',
            name='cover',
        ),
        migrations.RemoveField(
            model_name='school',
            name='slug',
        ),
        migrations.AlterField(
            model_name='school',
            name='address',
            field=models.CharField(blank=True, default='No address', max_length=255),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='school',
            name='logo',
            field=models.ImageField(blank=True, null=True, upload_to='school_logos/'),
        ),
        migrations.DeleteModel(
            name='Student',
        ),
    ]
