# Generated by Django 5.2.6 on 2025-09-29 08:27

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('academics', '0002_school_alter_classroom_school_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddIndex(
            model_name='classroom',
            index=models.Index(fields=['school', 'name'], name='academics_c_school__339c02_idx'),
        ),
        migrations.AddIndex(
            model_name='classroom',
            index=models.Index(fields=['school'], name='academics_c_school__2d3cea_idx'),
        ),
        migrations.AddIndex(
            model_name='studentprofile',
            index=models.Index(fields=['school'], name='academics_s_school__9dc3cf_idx'),
        ),
        migrations.AddIndex(
            model_name='studentprofile',
            index=models.Index(fields=['classroom'], name='academics_s_classro_70108e_idx'),
        ),
        migrations.AddIndex(
            model_name='studentprofile',
            index=models.Index(fields=['section'], name='academics_s_section_7f66b5_idx'),
        ),
        migrations.AddIndex(
            model_name='studentprofile',
            index=models.Index(fields=['school', 'classroom'], name='academics_s_school__232fcd_idx'),
        ),
        migrations.AddIndex(
            model_name='subject',
            index=models.Index(fields=['school', 'name'], name='academics_s_school__e80999_idx'),
        ),
        migrations.AddIndex(
            model_name='subject',
            index=models.Index(fields=['school'], name='academics_s_school__a86b39_idx'),
        ),
    ]
