# Generated by Django 5.2.6 on 2025-09-29 08:57

import django.db.models.deletion
from django.db import migrations, models


def copy_academics_schools_to_schools(apps, schema_editor):
    # Backfill schools into schools_school with the SAME IDs as academics_school
    OldSchool = apps.get_model('academics', 'School')
    NewSchool = apps.get_model('schools', 'School')

    for old in OldSchool.objects.all():
        if not NewSchool.objects.filter(id=old.id).exists():
            # address in schools is CharField(255); academics used TextField
            addr = (old.address or '')[:255]
            NewSchool.objects.create(id=old.id, name=old.name, address=addr)


class Migration(migrations.Migration):

    dependencies = [
        ('academics', '0003_classroom_academics_c_school__339c02_idx_and_more'),
        ('schools', '0003_remove_school_cover_remove_school_slug_and_more'),
    ]

    operations = [
        migrations.RunPython(copy_academics_schools_to_schools, migrations.RunPython.noop),
        migrations.AlterField(
            model_name='studentprofile',
            name='school',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='students', to='schools.school'),
        ),
        migrations.AlterField(
            model_name='classroom',
            name='school',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='classrooms', to='schools.school'),
        ),
        migrations.AlterField(
            model_name='subject',
            name='school',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='subjects', to='schools.school'),
        ),
        migrations.DeleteModel(
            name='School',
        ),
    ]
