# Generated by Django 4.2.7 on 2025-10-09 14:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0006_profile_designation'),
        ('academics', '0005_studentprofile_guardian_studentprofile_guardian_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='teacherassignment',
            name='teacher',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='assignments', to='users.profile'),
        ),
    ]
