# Generated by Django 4.2.7 on 2025-11-15 08:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('academics', '0007_alter_teacherassignment_teacher'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='studentprofile',
            options={'ordering': ['roll_number']},
        ),
    ]
