# Generated by Django 4.2.7 on 2026-01-10 10:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('academics', '0009_studentprofile_blood_group'),
    ]

    operations = [
        migrations.AddField(
            model_name='studentprofile',
            name='group',
            field=models.CharField(blank=True, choices=[('science', 'Science'), ('arts', 'Arts'), ('commerce', 'Commerce')], max_length=20, null=True),
        ),
    ]
