# Generated by Django 4.2.7 on 2026-01-13 17:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('academics', '0010_studentprofile_group'),
    ]

    operations = [
        migrations.AddField(
            model_name='subject',
            name='classrooms',
            field=models.ManyToManyField(blank=True, related_name='subjects', to='academics.classroom'),
        ),
    ]
