# Generated by Django 4.2.7 on 2026-01-14 03:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('academics', '0011_subject_classrooms'),
    ]

    operations = [
        migrations.AddField(
            model_name='subject',
            name='sections',
            field=models.ManyToManyField(blank=True, related_name='subjects', to='academics.section'),
        ),
    ]
