# Generated by Django 4.2.7 on 2026-02-19 23:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('schools', '0003_remove_school_cover_remove_school_slug_and_more'),
        ('academics', '0012_subject_sections'),
    ]

    operations = [
        migrations.CreateModel(
            name='StudentYearRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('roll_number', models.CharField(blank=True, max_length=50, null=True)),
                ('academic_year', models.CharField(max_length=9)),
                ('status', models.CharField(choices=[('promoted', 'Promoted'), ('retained', 'Retained'), ('not_passed', 'Not Passed')], default='promoted', max_length=20)),
                ('examination_id', models.IntegerField(blank=True, null=True)),
                ('result_cgpa', models.FloatField(blank=True, null=True)),
                ('result_grade', models.CharField(blank=True, max_length=5, null=True)),
                ('percentage', models.FloatField(blank=True, null=True)),
                ('rank', models.IntegerField(blank=True, null=True)),
                ('promoted_on', models.DateTimeField(blank=True, null=True)),
                ('meta', models.JSONField(blank=True, null=True)),
                ('classroom', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='year_records', to='academics.classroom')),
                ('promoted_to_classroom', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='promoted_year_records', to='academics.classroom')),
                ('school', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='student_year_records', to='schools.school')),
                ('section', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='year_records', to='academics.section')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='year_records', to='academics.studentprofile')),
            ],
            options={
                'ordering': ['-academic_year', 'student_id'],
                'indexes': [models.Index(fields=['school', 'academic_year'], name='academics_s_school__4b2eeb_idx'), models.Index(fields=['student', 'academic_year'], name='academics_s_student_8b4f6f_idx')],
                'unique_together': {('student', 'academic_year')},
            },
        ),
    ]
