# Generated by Django 5.2.6 on 2025-09-29 08:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('academics', '0003_classroom_academics_c_school__339c02_idx_and_more'),
        ('attendance', '0001_initial'),
        ('schools', '0003_remove_school_cover_remove_school_slug_and_more'),
    ]

    operations = [
        migrations.AddIndex(
            model_name='attendancerecord',
            index=models.Index(fields=['school', 'date'], name='attendance__school__8edf1d_idx'),
        ),
        migrations.AddIndex(
            model_name='attendancerecord',
            index=models.Index(fields=['school'], name='attendance__school__598dad_idx'),
        ),
        migrations.AddIndex(
            model_name='attendancerecord',
            index=models.Index(fields=['date'], name='attendance__date_337b1d_idx'),
        ),
    ]
